### ISSUE TITLE
Pertanyaan Pengumpulan Laporan

### ISSUE THREAD

**Issue by CitraAdiNegara** [polinema-gui/tugas#3]
Assalamualaikum pak, maaf mengganggu waktunya. Pak untuk pengumpulan tugas "Dokumentasikan alur program, dapat menggunakan flowchart atau pseudocode. Sertakan juga narasi bagaimana jalannya alur aplikasi dalam format file PDF dengan nama tugas-2015-03.pdf" pengumpulannya bisa menyusul apa tidak ? Soalnya saya sama Nurul ada keperluan organisasi kampus yang mendesak (Latihan Dasar Kepemimpinan) tetapi untuk Tugas VB nya sudah selesai. Bagaimana pak, Apakah boleh ?
Terima kasih, Wassalam

**Comment by dhanifudin** [comment]
Waalaykumsalam, silahkan commit dulu apa saja yang sudah selesai dikerjakan

**Comment by devintachr** [comment]
selamat malam pak, maaf mengganggu
saya mau commit tugas saya tetapi github desktop tidak deteck folder tugas saya, bagaimana mengatasinya pak? terimakasih

**Comment by dhanifudin** [comment]
silahkan buat isu baru, dan disertai hasil screenshootnya
